// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUxfQjL0mZCofa3ql0ZIskaUsOLDY4AW8',
    appId: '1:1032931285619:web:6ad4f0bc8ed21373c8a806',
    messagingSenderId: '1032931285619',
    projectId: 'fir-test-228',
    authDomain: 'fir-test-228.firebaseapp.com',
    storageBucket: 'fir-test-228.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5sLZ35fTb_DNMLRNoVi2m8UeZuIkyVV4',
    appId: '1:1032931285619:android:add631da83b2f5ddc8a806',
    messagingSenderId: '1032931285619',
    projectId: 'fir-test-228',
    storageBucket: 'fir-test-228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDia0rP2c2T3SOlZTUXomUhUiRUlj03FsE',
    appId: '1:1032931285619:ios:21f7b281faf03b58c8a806',
    messagingSenderId: '1032931285619',
    projectId: 'fir-test-228',
    storageBucket: 'fir-test-228.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDia0rP2c2T3SOlZTUXomUhUiRUlj03FsE',
    appId: '1:1032931285619:ios:21f7b281faf03b58c8a806',
    messagingSenderId: '1032931285619',
    projectId: 'fir-test-228',
    storageBucket: 'fir-test-228.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUxfQjL0mZCofa3ql0ZIskaUsOLDY4AW8',
    appId: '1:1032931285619:web:86535d51d7c1f86ec8a806',
    messagingSenderId: '1032931285619',
    projectId: 'fir-test-228',
    authDomain: 'fir-test-228.firebaseapp.com',
    storageBucket: 'fir-test-228.firebasestorage.app',
  );
}
